{application,nerves_io_rf24,
             [{applications,[kernel,stdlib,elixir,logger,elixir_make]},
              {description,"Elixir access to the nRF24L01+ over SPI\n"},
              {modules,['Elixir.Nerves.IO.RF24',
                        'Elixir.Nerves.IO.RF24.Framing',
                        'Elixir.Nerves.IO.RF24.Framing.None',
                        'Elixir.Nerves.IO.RF24.State',
                        'Elixir.Nerves.IO.Supervisor',
                        'Elixir.Nerves.UART.Framing.FourByte',
                        'Elixir.Nerves.UART.Framing.Line',
                        'Elixir.Nerves.UART.Framing.Line.State']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
